- scripts/aerospike-client-c.sh
https://github.com/aerospike/aerospike-client-nodejs/issues/72
> Fix support for Debian 8

- docs/datamodel.md
> ttl unit of time info

- docs/largelist.md
Just fixed a small typo where remove was typed in a delete
> Method Name Change

- examples/logging.js
- examples/package.json
- lib/llist.js
- lib/utils.js
- package.json
- test/client.js
- test/put.js
- test/stress/perfdata.js
https://github.com/feross/standard/blob/master/CHANGELOG.md#900---2017-02-28
> Upgrade to Standard v9

- lib/key.js
- src/main/util/conversions.cc
- test/key.js
- test/put.js
> Support creating new key from ns + digest

- package.json
- src/include/log.h
- src/main/client/batch_exists.cc
- src/main/client/batch_get.cc
- src/main/client/batch_select.cc
- src/main/util/conversions.cc
- src/main/util/log.cc
> Run cppcheck static analysis on native extension code

- scripts/aerospike-client-c.sh
fix "check to see if there is an installed client"
> fix check_lib_path

- lib/client.js
- src/main/policy.cc
> Add socket timeout to query policy

- History.md
- aerospike-client-c.ini
- aerospike-client-c.sha256
- docs/api-changes.md
- lib/client.js
- lib/lists.js
- lib/query.js
- lib/scan.js
- src/main/config.cc
- src/main/operations.cc
- src/main/policy.cc
- src/main/query.cc
- test/cdt_list.js
- test/index.js
- test/query.js
- test/test_helper.js
C client release notes: http://www.aerospike.com/download/client/c/notes.html#4.2.0
Note: This client version includes several breaking changes.
> Update to C client v4.2

- lib/client.js
- lib/event_loop.js
- test/client.js
> Release event loop on #close even if client not connected

- lib/policies/apply_policy.js
- lib/policies/base_policy.js
- lib/policies/batch_policy.js
- lib/policies/info_policy.js
- lib/policies/map_policy.js
- lib/policies/operate_policy.js
- lib/policies/query_policy.js
- lib/policies/read_policy.js
- lib/policies/remove_policy.js
- lib/policies/scan_policy.js
- lib/policies/write_policy.js
- lib/policy.js
> Update documentation for client policies

- lib/policies/operate_policy.js
- src/main/policy.cc
- test/operate.js
- test/put.js
Resolves #229.
Requires C client version v4.3.1 or later.
> Operate exists policy

- History.md
- src/include/conversions.h
- src/main/operations.cc
- src/main/util/conversions.cc
- test/operate.js
Aerospike.operations.write() should support all data types including GeoJSON, List & Map.
resolves issue #235
> Fix Client#operate write op to support all data types

- test/index.js
Avoid race condition between `Client#indexRemove()` tests and the `afterEach` hook for the "secondary indexes" test suite which also removes the index.
> Fix race condition in indexRemove tests

- README.md
- src/include/conversions.h
- src/main/commands/batch_read_async.cc
- src/main/commands/exists_async.cc
- src/main/commands/get_async.cc
- src/main/commands/operate_async.cc
- src/main/commands/select_async.cc
- src/main/operations.cc
- src/main/util/conversions.cc
Fix potential memory corruption issue in handling of setOrder/sort list operations. Resolves #216.
> Fix setOrder/Sort list operations

- package.json
- src/include/log.h
- src/main/commands/apply_async.cc
- src/main/commands/batch_read_async.cc
- src/main/commands/exists_async.cc
- src/main/commands/get_async.cc
- src/main/commands/job_info.cc
- src/main/commands/operate_async.cc
- src/main/commands/put_async.cc
- src/main/commands/query_async.cc
- src/main/commands/remove_async.cc
- src/main/commands/scan_async.cc
- src/main/commands/select_async.cc
- src/main/commands/udf_register.cc
- src/main/config.cc
- src/main/events.cc
- src/main/operations.cc
- src/main/query.cc
- src/main/util/conversions.cc
- test/predexp.js
Fix memory leaks detected by running Valgrind
> Fix memory leaks

- package-lock.json
- package.json
- src/main/aerospike.cc
- src/main/config.cc
- src/main/util/conversions.cc
* Replace Object::Has with Nan::Has.
* Replace Object::GetOwnPropertyNames with Nan::GetOwnPropertyNames.
* Redo module initialization using NAN_MODULE_INIT.
Ref.: https://travis-ci.org/aerospike/aerospike-client-nodejs/jobs/523788617
Resolves #296.
> Node.js 12 compatibility

- package-lock.json
- package.json
> Greenkeeper/mocha 6.2.2

- README_WINDOWS.md
> Update prerequisites & add FAQ

- CHANGELOG.md
- lib/policies/base_policy.js
- src/main/policy.cc
- test/enterprise.js
- test/generators/value.js
- test/policy.js
- test/remove.js
This feature requires Enterprise Server versions >= 4.8.
> Support compressed commands and responses

- CHANGELOG.md
- src/main/stats.cc
- test/stats.js
Adds total opened/closed connection counts per node to client statistics.
> Add opened/closed connection stats

- lib/aerospike.js
- lib/policy.js
> Minor apidoc updates

- package-lock.json
- package.json
Update several dependencies to address potential security issues.
> Update codecov, lodash dependencies

- scripts/aerospike-client-c.sh
- scripts/os_version
> Use EL7 builds on Amazon Linux [v3.x]

- scripts/aerospike-client-c.sh
- scripts/os_version
> Use EL7 builds on Amazon Linux

- benchmarks/logging.js
- benchmarks/main.js
- benchmarks/package-lock.json
- benchmarks/worker.js
- package-lock.json
> Fix benchmark logging

- README.md
> Workaround for Apple M1 chip Macs in Readme

- .github/workflows/build.yml
- lib/policies/query_policy.js
- package-lock.json
- package.json
- src/main/policy.cc
- test/command_queue.js
- test/policy.js
- test/scan.js
(CLIENT-1718) Support failOnClusterChange for query policy
> PR: Client-Nodejs 4.0.2 release

- docker/Dockerfile.alpine
- scripts/build-commands.sh
- typings/index.d.ts
The items appear twice causing confusion (`MapsOrder` vs. `MapOrder`, etc.)
> Fix duplicate map policy items it the TS

- docker/Dockerfile.alpine
- docker/Dockerfile.lambda
- lib/record.js
This example is in production serving millions of requests per day.
> Add Dockerfile example for AWS Lambda

- test/batch_write.js
Conflict was not resolved before merging
> CLIENT-2146

- .github/workflows/windows-build.yml
- binding.gyp
- package.json
- scripts/build-c-client.ps1
- scripts/postinstall.js
Includes Zohar's changes sent to me on slack.
> CLIENT-2148

- scripts/prebuiltBinding.js
- test/batch_write.js
CLIENT-2011
Fixed test cases that were reverted on previous commit
Fixed lint errors
> Fixed test cases and lint errors

- src/main/cdt_ctx.cc
> Re-implemented switch from if statement

- lib/client.js
CLIENT-1819
Corrected parameters to include a list of keys rather than a list of records.
> Fixed Documentation for batchRemove

- src/main/util/conversions.cc
- test/exp.js
CLIENT-2187
Added test cases to exp.js for map and list equality.
Changed map type used in expressions.
> Changed map type used in expressions

- lib/exp.js
Functions were being listed as methods
parameters now appear on API documentation
> CLIENT-2237

- lib/policies/query_policy.js
- lib/policies/scan_policy.js
- src/main/policy.cc
CLIENT-2347
Added queryPolicy property 'replica'.
Added scanPolicy property 'replica'.
Added support for rack aware queries and scans.
> CLIENT-2347

- lib/cdt_context.js
- lib/client.js
- src/include/client.h
- src/include/operations.h
- src/main/cdt_ctx.cc
- src/main/client.cc
- test/cdt_context.js
- test/client.js
CLIENT-1990
Added CDT context serialization and deserialization. Added maximum and minimum values for Index and Rank CDT context.
> CLIENT-1990

- lib/query.js
- lib/scan.js
- src/main/query.cc
- src/main/scan.cc
- test/query.js
- test/scan.js
CLIENT-1303
Added the ‘TTL' property to the query and scan classes.
> Added the ‘TTL' property to the query and scan classes.

- lib/client.js
- lib/query.js
- src/main/config.cc
- src/main/util/conversions.cc
CLIENT-2466
Added additional input validation.
> Added additional input validation.

- jsdoc.json
Switched from Ink-docstrap to Docdash for API documentation generation.
> Switched from Ink-docstrap to Docdash

- lib/exp.js
- src/include/conversions.h
- src/main/expressions.cc
- src/main/util/conversions.cc
- test/exp.js
CLIENT-2378
Add exp.inf and exp.wildcard methods
Add testing for exp.inf, exp.nil, and exp.wildcard
> Add exp.inf and exp.wildcard methods

- src/main/async.cc
- src/main/commands/batch_apply.cc
- src/main/commands/batch_exists.cc
- src/main/commands/batch_get.cc
- src/main/commands/batch_remove.cc
- src/main/commands/batch_select.cc
- test/batch_remove.js
- test/batch_write.js
CLIENT-2629
Added logic to ignore AEROSPIKE_BATCH_FAILED in cases where records are returned for all batch commands
> Fixed AEROSPIKE_BATCH_FAILED error issue

- binding.gyp
- lib/exp.js
- src/include/enums.h
- src/main/aerospike.cc
- src/main/enums/exp_read_flags.cc
- src/main/enums/exp_write_flags.cc
- test/exp.js
CLIENT-2592
Added exp.expWriteFlags and exp.expReadFlags
> Added exp.expWriteFlags and exp.expReadFlags

- lib/exp.js
- src/main/enums/exp_enum.cc
- test/exp.js
> Added exp.recordSize

- lib/client.js
- lib/filter.js
- src/main/enums/index.cc
- src/main/query.cc
- src/main/util/conversions.cc
- test/index.js
- test/query.js
CLIENT-2587
Added Blob Secondary index support
Added client.createBlobIndex
Fixed Javascript Maps to place non-string indexes on server
> Added Bolb Secondary Index support.

- lib/config.js
- src/main/config.cc
CLIENT-1421
Added maxErrorRate and errorRateWindow configurations. Fixed bug with tenderInteval
> Added maxErrorRate and errorRateWindow configurations

- .gitmodules
- binding.gyp
- lib/policies/query_policy.js
- lib/policy.js
- lib/query_duration.js
- src/include/enums.h
- src/main/aerospike.cc
- src/main/enums/query_duration.cc
- src/main/policy.cc
- test/query.js
- typings/index.d.ts
CLIENT-2822
Added expectedDuration as QueryPolicy member
Added queryDuration enum to aerospike.policy
Added unit testing for expectedDuration in queries
> Added expectedDuration as QueryPolicy member

- .gitmodules
- lib/policies/batch_policy.js
- lib/policies/batch_read_policy.js
- lib/policies/operate_policy.js
- lib/policies/read_policy.js
- src/main/policy.cc
- test/batch_read.js
- test/get.js
- test/operate.js
CLIENT-2829
readTouchTtlPolicies was added to the following policies: operate
read
batch_read
batch
Unit tests added to specified test files
Added API documentation
> Added readTouchTtlPercent to various policies

- lib/policy.js
- src/main/config.cc
- ts-test/package-lock.json
- ts-test/package.json
- ts-test/tests/config.ts
- typings/index.d.ts
CLIENT-3396
Added txnRoll and TxnVerify to config policies.
> Added txnRoll and TxnVerify to config policies

- lib/policies/apply_policy.js
- lib/policies/remove_policy.js
- lib/policies/write_policy.js
- typings/index.d.ts
CLIENT-3388
Added missing Replica field for write, remove, and apply policies.
> Added missing Replica field for write, remove, and apply policies.

- src/main/util/conversions_batch.cc
CLIENT-3390
Fixed issue with batchWrite failing to parse the UDF parameter in BATCH_APPLY records
> Fixed issue with batchWrite failing to parse the UDF parameter in BATCH_APPLY records

- lib/policies/apply_policy.js
- lib/policies/batch_apply_policy.js
- lib/policies/batch_write_policy.js
- lib/policies/write_policy.js
- package-lock.json
- src/main/policy.cc
- test/udf.lua
- ts-test/tests/apply.ts
- ts-test/tests/batch_apply.ts
- ts-test/tests/batch_write.ts
- ts-test/tests/policy.ts
- ts-test/tests/put.ts
- typings/index.d.ts
CLIENT-3266
Added onLockingOnly parameter to apply, write, batchApply, and batchWrite policies.
> Added onLockingOnly parameter to apply, write, batchApply, and batchWrite policies.
