scripts/aerospike-client-c.sh

Add support for building aerospike-client-nodejs in Fedora 20-22. Fixes #84

Add support for Fedora 20-22

---

lib/aerospike.js
lib/llist.js

top level explicit variable declarations are missing and strict mode is not enabled.
variables are leaking passively to global scope which can cause collision with other libraries and user modules.
strict mode should also be enabled in my opinion.
list of restrained variables: `LargeList, execute, Info,query, createIntegerIndex, createStringIndex, createGeo2DSphereIndex, parseOperateArgs, add, append, prepend ,`
Allowing instances in LargeLists.
in the current formation this is not possible:
``` javascript
var list1 = client.LargeList({ns: 'test', set: 'test', key: 'my_key1'}, 'ldt_bin');
var list2 = client.LargeList({ns: 'test', set: 'test', key: 'my_key2'}, 'ldt_bin');
```
Because LargeList stores arguments on itself (shared among all calls).
Generally speaking this is an anti pattern. …

Preventing leakage to global scope + allowing LargeList instances

---

.travis.yml
README.md

`stable` alias has been deprecated. 
From nvm documentation:
>  - `stable`: this alias is deprecated, and only truly applies to `node` `v0.12` and earlier. Currently, this is an alias for `node`.

Test latest stable + show travis badge

---

scripts/os_version

Update os_version detection script with explicit detection for
Elementary OS (v0.4) and LinuxMint 17/18.
For other Linux distros that use /etc/os-release but have a distro ID
that we do not explicity detect, try to guess the best client based on
the ID_LIKE attribute instead.
Closes #166
Closes #170

Update os_version script to support additional Linux distros

---

lib/client.js
lib/job.js
lib/query.js
lib/scan.js
test/client.js

Ensure all callbacks are done asynchronously

---

lib/aerospike_error.js
lib/client.js
test/client.js

Resolves #189 
Adds a `captureStackTraces` setting to the client, which, when set to `true`, causes the client to capture the stack trace before any client command is being executed. If an error occurs during command execution, the stack trace will be set in the `AerospikeError` instance returned in the callback.
Capturing a stack trace for every client command is quite expensive, so this option should only be enabled temporarily for debugging purposes.
This setting can be enabled for all new client instances by setting the `AEROSPIKE_DEBUG_STACKTRACES` environment variable to any non-empty value.
Example of a typical stack trace with `captureStackTraces` _disabled_:
```
{ AerospikeError: AEROSPIKE_ERR_RECORD_NOT_FOUND
at Function.AerospikeError.fromASError …
```

Capture better stacktraces

---

lib/client.js
src/main/policy.cc

Adds the following properties for batch policy:
* `consistencyLevel` (new in C client v4.1.6)
* `allowInline`
* `sendSetName`

Expose new consistency level in batch policy

---

History.md
aerospike-client-c.ini
aerospike-client-c.sha256
binding.gyp
lib/client.js
src/include/client.h
src/include/events.h
src/main/aerospike.cc
src/main/client.cc
src/main/events.cc

Set up a callback for AS cluster events. Client will emit the following
events:
* nodeAdded - a new cluster node was detected
* nodeRemoved - an existing node was removed from the cluster
* disconnected - the client has lost connection to all cluster nodes
Requires Aerospike C client v4.1.8.
Closes #145

Implement cluster event callbacks

---

lib/aerospike.js
lib/aerospike_error.js
lib/client.js
lib/commands/command.js
lib/commands/exists_command.js
lib/event_loop.js
lib/filter.js
lib/index_job.js
lib/info.js
lib/job.js
lib/lists.js
lib/maps.js
lib/operations.js
package.json

Use [bindings](https://www.npmjs.com/package/bindings) to resolve native addon instead of hard-coding the path:
require('../build/Release/aerospike.node')
Becomes:
require('bindings')('aerospike.node')

Use bindings module to resolve native addon

---

lib/aerospike.js
lib/client.js
lib/commands/batch_command.js
lib/commands/command.js
lib/commands/exists_command.js
lib/commands/index.js
lib/commands/read_record_command.js
lib/commands/stream_command.js
lib/commands/write_record_command.js
lib/error.js
lib/job.js
lib/query.js
lib/scan.js
src/main/util/conversions.cc
test/command.js
test/error.js

In [v4.3.3](https://www.aerospike.com/download/client/c/notes.html#4.3.3), the Aerospike C client added a new `in_doubt` flag to the `as_error` struct, to indicate if a write command may have completed even though an error was returned. This scenario can occur on a client timeout for a command that has been sent to the server. This PR exposes the new flag through the `AerospikeError` class.
Instances of `AerospikeError` now also reference the `Command` instance which generated the error. This is useful as the command may contain additional information such as the record key for which the error occurred.

Improve AerospikeError & add new inDoubt flag

---

lib/lists.js
lib/maps.js
src/main/operations.cc
test/lists.js
test/maps.js
test/query.js
test/remove.js
test/test_helper.js
test/truncate.js

Implements support for 6 new list/map "relative range" operations:
* `lists.getByValueRelRankRange` - retrieves list items nearest to value and greater, by relative rank range
* `lists.removeByValueRelRankRange` - removes list items nearest to value and greater, by relative rank range
* `maps.getByKeyRelIndexRange` - retrieves map items nearest to key and greater, by relative index range
* `maps.getByValueRelRankRange` - retrieves map items nearest to value and greater, by relative rank range
* `maps.removeByKeyRelIndexRange` - removes map items nearest to key and greater, by relative index range
* `maps.removeByValueRelRankRange` - removes map items nearest to value and greater, by relative rank range
Requires C client v4.3.14 and server v4.3 or later. (Unit tests for new operations …

Support CDT Relative Range OPs

---

CHANGELOG.md
lib/lists.js
lib/maps.js
lib/policies/map_policy.js
src/include/conversions.h
src/main/enums/lists.cc
src/main/enums/maps.cc
src/main/operations.cc
src/main/util/conversions.cc
test/lists.js
test/maps.js

* Add new list policy write flags NO_FAIL & PARTIAL
* Add new map policy write flags, incl. NO_FAIL & PARTIAL to replace write mode

Updated CDT op policy: Add list/map NO_FAIL/PARTIAL flags, new map write flags

---

lib/policies/batch_policy.js
lib/policies/operate_policy.js
lib/policies/query_policy.js
lib/policies/read_policy.js
src/main/policy.cc
test/batch_read.js
test/get.js
test/operate.js
test/query.js

When setting `ReadPolicy#deserialize` to `false` (default is `true`) the
client will return CDT (list/map) bins as raw byte buffers.

Support "deserialize" read policy setting

---

CHANGELOG.md
lib/config.js
src/main/config.cc

Adds a new useAlternateAccessAddress config flag, which, when set to
true`, instructs the client to use the alternate access address published
by the server(s).
This was _kind_ _of_ supported in client v3.4 and earlier but required
that the client's seed address list contains the complete list of the
alternate access addresses of all cluster nodes. The v3.4 and earlier
clients were not able to automatically detect new cluster hosts, not
included in the seed address list, using the alternate access address.
This partial support for alternate-access-address was broken in Node.js
client v3.5.0 (using C client v4.3.14) due to the introduction of a new
feature that automatically detects if the seed address used by the
client is a load balancer address. Due to this change, the v3.5.0 and
later …

Support using server's alternate-access-address

---

test/command_queue.js
test/test_helper.js
test/util/options.js
test/util/run_in_new_process.js

Some test cases that are launched in a separate Node.js process fail if the server uses user auth. Need to pass all the client config, incl. user/pwd, through to the spawned process.

Pass client config through to test cases launched in separate process

---

binding.gyp

Link to ssl on Linux, to resolve linking problem that otherwise arises on Alpine Linux. See #286.

Fix Linux build by linking to ssl

---

docker/Dockerfile.alpine

Update Dockerfile.alpine to:
* Alpine Linux 3.11
* Node.js 12
* Aerospike Node.js client 3.14.0
* Aerospike C client 4.6.10
Resolves #332.

Update Dockerfile for Alpine 3.11 & latest client version

---

lib/bigint.js
lib/key.js
package.json
src/main/util/conversions.cc
test/bigint.js
test/key.js
test/put.js
test/test_helper.js

Adds support for creating record keys using the BigInt data type as well as reading/writing BigInt bin values. BigInt was introduced in Node.js 10.4, so on older Node.js versions, only regular integers (`Number` type) can be used.
Resolves #347.
Todo:

Support BigInt as record key & bin value

---

.travis/aerospike.conf
CHANGELOG.md
lib/policies/scan_policy.js
lib/scan.js
src/main/policy.cc
src/main/scan.cc
test/scan.js

Adds a new `maxRecords` option to scan policies:
> Approximate number of records to return to client. This number is divided by the number of nodes involved in the scan. The actual number of records returned may be less than maxRecords if node record counts are small and unbalanced across nodes.
>
> Requires Aerospike Server version >= 4.9.
> Default: 0 (do not limit record count)

Support maxRecords scan policy

---

benchmarks/alerts.js
benchmarks/stats.js
benchmarks/worker.js
examples/geospatialMonteCarlo.js
lib/event_loop.js
lib/filter.js
lib/info.js
lib/lists.js
lib/maps.js
lib/utils.js
test/command_queue.js
test/generators/key.js
test/generators/metadata.js
test/generators/put.js
test/generators/record.js
test/generators/util.js
test/generators/value.js
test/predexp.js
test/stress/perfdata.js
test/util/run_in_new_process.js

This rule is on its way into the latest Standard ☺️
ref: https://github.com/standard/eslint-config-standard/pull/166
-----
This syntax is compatible with Node.js >=4.0, which is the indicated support in your package.json

Use object shorthand for properties

---

.appveyor.yml
.travis.yml
README_WINDOWS.md

Make any changes necessary (if any) to support building and running the client with Node.js 14, which was announced on 2020-04-22: https://nodejs.org/en/blog/release/v14.0.0/.

Support for Node.js 14

---

.travis/aerospike.conf
CHANGELOG.md
binding.gyp
lib/aerospike.js
lib/hll.js
lib/policies/hll_policy.js
src/include/enums.h
src/include/operations.h
src/main/aerospike.cc
src/main/enums/hll_enum.cc
src/main/hll_operations.cc
src/main/operations.cc
test/hll.js
test/util/statefulAsyncTest.js

Add support for new HyperLogLog data type and operations introduced in server version 4.9:

HyperLogLog operations

---

CHANGELOG.md
benchmarks/main.js
package-lock.json
package.json
src/include/conversions.h
src/include/query.h
src/main/commands/query_apply.cc
src/main/commands/query_async.cc
src/main/commands/query_background.cc
src/main/commands/query_foreach.cc
src/main/query.cc
src/main/util/conversions.cc
test/batch_exists.js
test/batch_get.js
test/batch_read.js
test/batch_select.js
test/generators/put.js
test/predexp.js
test/query.js
test/scan.js
test/stress/perfdata.js
test/stress/query.js
test/stress/scan.js
test/truncate.js

Prevent memory leak from keeping duplicate copies of the bin name and
string predicate values in memory after the query is finished.
Resolves #370.

Fix memory leaks when running queries

---

lib/config.js
lib/typedefs.js
src/main/config.cc

As of v3.16.1, the only way to specify a tlsname when establishing a TLS encrypted server connection is to specify the seed hosts as a single string, e.g. 
```
const hosts = '192.168.0.1:example.com:3000,192.168.0.2:example.com:3000'
const client = await Aerospike.connect({ hosts })
```
This PR adds support for setting the tlsname via the array of `Host` objects instead:
```
const hosts = [
{ addr: '192.168.0.1', port: 3000, tlsname: 'example.com' },
{ addr: '192.168.0.2', port: 3000, tlsname: 'example.com' }
]
const client = await Aerospike.connect({ hosts })
```
It also generally improves the documentation for the `Config#hosts` property by adding more examples, including examples with `tlsname`.
Resolves #377.

Support setting tlsname using Host object

---

lib/policies/apply_policy.js
src/main/policy.cc
test/policy.js

The server does not support these fields in UDF calls. The read-modify-write usage model can still be enforced inside the UDF code itself. The `as_policy_apply.gen` property is being dropped in C client v5.

Remove ApplyPolicy#gen

---

lib/utils.js
test/utils.js

As stated in this TLS PR here #382, the attribute is called `tlsname`. The current version of the `config.cc` also makes use of `tlsname` like e.g. here in [src/main/config.cc](https://github.com/aerospike/aerospike-client-nodejs/blob/master/src/main/config.cc#L77).
However, in `lib/utils.js` [here](https://github.com/aerospike/aerospike-client-nodejs/blob/719b259c81a613a13424d4f133b5d9a8adc53d41/lib/utils.js#L37), the attribute is `tls` and not `tlsname`.

fix: tls and tlsname mismatch

---

lib/query.js

Query#background takes a WritePolicy instead of a QueryPolicy as argument.
Fixes CLIENT-1425.

CLIENT-1425: Fix docs for Query#background policy argument

---

lib/client.js

When sending an empty info command, the server returns a set of default
info values, not *all* info values.

CLIENT-1428: Fix docs for empty info commands

---

binding.gyp
lib/client.js
lib/event_loop.js
src/main/aerospike.cc
test/client.js

After closing aerospike clients without releasing the event loop the
wakeup trigger in aerospike's event loop is keeping the node.js process
alive. This is problem for test suits running in mocha as mocha does not
call `process.exit()` by default, which has to be worked around.
This patch implements a cleaner behavior by keeping aerospike's event
loop alive while preventing it from keeping node's event loop alive.
Similar to the behavior when calling `process.exit()` the aerospike's
event loop is not released explicitly.
This might be a good default behavior.
I have not tested this beyond opening a connection to aerospike and closing this. So there might be other handles that leak out of a used connection.

Allow Exit

---

test/client.js
test/test_helper.js

Calling client.close() before client.connect() has been called is now an
error, rather than a no-op.
Addresses https://github.com/aerospike/aerospike-client-nodejs/pull/399#issuecomment-781753518.

Fix client #noserver test

---

test/info.js
test/test_helper.js

The `client#info()` command stopped working on the latest server version when using client authentication. The `client#info()` command has been deprecated since Node.js client 3.11 and will be removed in the next (major) client version. For now, just skip the tests if client authentication is used.

Skip client#info() tests when using authentication

---

lib/client.js

CLIENT-1428: Clarify info command docs when no query is specified (maint/3.x)

---

scripts/build-c-client.ps1

Using the old method, you can build a package only with english MSBuild localization. This commit fix it.

Fix checking build result on Windows

---

README.md
lib/aerospike.js
lib/batch_type.js
package-lock.json
package.json
scripts/build-commands.sh
test/batch_write.js
typings/index.d.ts

It fixes the following:
[CLIENT-1745] Running node.js client 5.0.0 on Alpine 3.15 + node 17.9 results with an error
[CLIENT-1746] Node.js batch type js object and documentation incomplete
[CLIENT-1745]: https://aerospike.atlassian.net/browse/CLIENT-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLIENT-1746]: https://aerospike.atlassian.net/browse/CLIENT-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PR: Client-nodejs 5.0.2 patch release

---

README.md
docker/Dockerfile.bullseye-slim
examples/put.js
examples/shared/cli.js

As this is supported, we install only minimal requirements and a pre-built package

Docker example for debian 11 container

---

ts-test/tests/batch_write.ts

CLIENT-3391
Fixes segmentation fault when using batchWrite with a single record as a command in a transaction.

Updated the C Client submodule.

---

src/main/util/conversions_batch.cc

CLIENT-3389
Fixed BATCH_APPLY and BATCH_REMOVE records not being configured for writes.
Removed redundant code in favor of the C Client.  No need to overwrite these values.

Fixed BATCH_APPLY and BATCH_REMOVE records not being configured for writes.
